## Numpy and pandas

- It is mostely commonly used python libraries for data science
- Numpy name breaks into two parts (Num + py)
- Num is denoted as numerical and py it was represented as python
- some also called as ArrayOriented computing because in numpy just like list in python you will be able to work on array kind of DataStructure 
- This package is mainly written for your scientific computing and data analysis


#### What is  the basic numpy object
- It is going to Ndimensional array
- sometime we also denoted as "ndarray"
- One important property about this is homogeneous array(stored in same kind of data("c" and "java" also homogeneous))(lists are heterogeneous means stored different kind of data structures like int and float and char)
- ex=[1,2,3](same datatype(all intiger))

#### Why Numpy(Numpy is kind like a list but ndarray)
- Fast (we do all the datascience analysis by just python list is one of main reason it is very fast)(in the backend everything runs into the c programming)
- Convinience(and second reason it's computing.it's very easy and conveninet )
- Ex:- we have list that is [1,2,3,4]
- -------------------------in general python program occurs or folloeing  looping 1+2=3 3+3=6 6+4=10 like that But Numpy parally works like 1+2=3 and 3+4=7 then add 3+7=10

- That the purpose Numpy is far the best to compare python list
- And Numpy also going to take less  storage,the way it is written it is very compact in comparison to your list


In [3]:
import numpy as np

In [4]:
np.array([1,2,3])

array([1, 2, 3])

In [5]:
type(np.array([1,2,3]))

numpy.ndarray

In [6]:
a=np.array([1,2,3.5])
a

array([1. , 2. , 3.5])

In [7]:
a.dtype

dtype('float64')

In [10]:
b=np.array([[4,5,6],[7,8,9]])
b

array([[4, 5, 6],
       [7, 8, 9]])

In [11]:
# dimentions of particular array
b.shape #(2 rows and 3 column)

(2, 3)

In [12]:
# total rows are present in that particular nparray
b.ndim

2

In [79]:
# without using for loop  we can give range 
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
c=range(100)

In [14]:
# Normal python list using for checking time for execution
%timeit [i**5 for i in c]

70.2 µs ± 2.58 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [16]:
# Let's check using numpy how much it would take
c_numpy=np.arange(1000)

In [17]:
%timeit c_numpy**5

6.85 µs ± 231 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [28]:
d=range(1000)
e=[i**2 for i in range(1000)]

In [29]:
%timeit list(map(lambda x,y:x*y,d,e))

243 µs ± 21.6 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [30]:
d1=np.array(d)
e1=np.array(e)

In [31]:
%timeit d1*e1

2.49 µs ± 73.4 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [32]:
# It shows begin with "0"
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [33]:
# But i want starting with 5
np.arange(5,10)

array([5, 6, 7, 8, 9])

In [34]:
#give space of 2
np.arange(3,10,2)

array([3, 5, 7, 9])

In [35]:
np.zeros((3,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [36]:
np.ones((3,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [38]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [39]:
np.full((3,3),2)

array([[2, 2, 2],
       [2, 2, 2],
       [2, 2, 2]])

In [40]:
np.full((3,3),2.2)

array([[2.2, 2.2, 2.2],
       [2.2, 2.2, 2.2],
       [2.2, 2.2, 2.2]])

In [42]:
#all floating value converted into intigers
np.full((3,3),2.2,dtype=np.int)

array([[2, 2, 2],
       [2, 2, 2],
       [2, 2, 2]])

In [44]:
# diagonal
np.diag([1,2,3,4])

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [46]:
f=np.array([1,2,3])

In [47]:
f

array([1, 2, 3])

In [111]:
# horizontally(rows) 3 lines filled with f[list],vertically 1 line (column)
np.tile(f,(3,1))

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [48]:
# 3 rows and 2 column filled wih same f[list]
np.tile(f,(3,2))

array([[1, 2, 3, 1, 2, 3],
       [1, 2, 3, 1, 2, 3],
       [1, 2, 3, 1, 2, 3]])

In [53]:
np.random.random()

0.802246927543056

In [54]:
# i want 2 to 50 random value
50*np.random.random() +2

48.97972132431036

In [56]:
# Create a matrix of random value
np.random.random([3,3])

array([[0.76562679, 0.81486022, 0.29969271],
       [0.20255844, 0.20051113, 0.14757553],
       [0.03865343, 0.35013547, 0.06720779]])

In [63]:
# I want print 1 to 50 but these range equally disturbed into 100 parts
a=np.linspace(1,50,100)

In [64]:
a

array([ 1.        ,  1.49494949,  1.98989899,  2.48484848,  2.97979798,
        3.47474747,  3.96969697,  4.46464646,  4.95959596,  5.45454545,
        5.94949495,  6.44444444,  6.93939394,  7.43434343,  7.92929293,
        8.42424242,  8.91919192,  9.41414141,  9.90909091, 10.4040404 ,
       10.8989899 , 11.39393939, 11.88888889, 12.38383838, 12.87878788,
       13.37373737, 13.86868687, 14.36363636, 14.85858586, 15.35353535,
       15.84848485, 16.34343434, 16.83838384, 17.33333333, 17.82828283,
       18.32323232, 18.81818182, 19.31313131, 19.80808081, 20.3030303 ,
       20.7979798 , 21.29292929, 21.78787879, 22.28282828, 22.77777778,
       23.27272727, 23.76767677, 24.26262626, 24.75757576, 25.25252525,
       25.74747475, 26.24242424, 26.73737374, 27.23232323, 27.72727273,
       28.22222222, 28.71717172, 29.21212121, 29.70707071, 30.2020202 ,
       30.6969697 , 31.19191919, 31.68686869, 32.18181818, 32.67676768,
       33.17171717, 33.66666667, 34.16161616, 34.65656566, 35.15

In [123]:
a.itemsize

8

In [124]:
# how much memory used a particular elements in terms of bytes
a.itemsize

8

In [68]:
# I want to change the shape.I want to make it 3d shape
np.arange(18).reshape (2,4,4)# It was creating that 3d kind of arrayforming
                             # And i was 2 values and 3*3 matrix

ValueError: cannot reshape array of size 18 into shape (2,4,4)

In [132]:
#checking it's working or not
b=np.arange(18).reshape (2,3,3)
b.shape

(2, 3, 3)

In [134]:
# We don't know exactly the dimention after 3 now we give -1 it's 
# adjust accordingly
np.arange(18).reshape(2,3,-1)

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]]])

In [135]:
a=np.array([2,4,6,8,10,12,14,16,18])

In [136]:
a

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [137]:
a[0]

2

In [138]:
a[1]

4

In [139]:
# i want bunde list these positions not like this code kindly observe
a[2,4,6]

IndexError: too many indices for array

In [140]:
a[[2,4,6]]

array([ 6, 10, 14])

In [141]:
# I want start from 2nd position to end in this array 
a[2:]

array([ 6,  8, 10, 12, 14, 16, 18])

In [142]:
# stop at 4th index
a[2:4]

array([6, 8])

In [143]:
# start to 0 to end but give space 2
a[1::2]

array([ 4,  8, 12, 16])

In [144]:
a=np.array([[1,2,3],[4,5,6],[7,8,9]])

In [145]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [146]:
# position of 2 and 2 value to the given index
a[2,2]

9

In [147]:
# i want the values greatherthan 2
a > 2

array([[False, False,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [148]:
# put some condition
a[(a>2)&(a<5)]

array([3, 4])

##### subset of array

In [149]:
a=np.arange(10)

In [150]:
b=a

In [151]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [152]:
b

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [153]:
b[0]=11

In [154]:
b

array([11,  1,  2,  3,  4,  5,  6,  7,  8,  9])

In [155]:
a

array([11,  1,  2,  3,  4,  5,  6,  7,  8,  9])

In [156]:
# the above arrays sharing the samememory location or not checking purpose that
# we can use shares_memory function
np.shares_memory(a,b)

True

In [160]:
# I don't want share same memory location,but both are them copying same object
a=np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [163]:
b=a.copy()

In [164]:
b

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [166]:
np.shares_memory(a,b)

False

In [169]:
a=np.array([[1,2,3],[4,5,6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [171]:
# I want to transpose means make all my row as columns and make all my columns
# as rows
a.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [172]:
b=np.array([[8,0,9],[10,11,12]])

In [173]:
b

array([[ 8,  0,  9],
       [10, 11, 12]])

In [174]:
# Comparing a values to b values
a==b

array([[False, False, False],
       [False, False, False]])

In [176]:
#vertical stack helps 2indexs merage into 1 index vertically
np.vstack((a,b))

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 8,  0,  9],
       [10, 11, 12]])

In [177]:
#horizontal stack
np.hstack((a,b))

array([[ 1,  2,  3,  8,  0,  9],
       [ 4,  5,  6, 10, 11, 12]])

##### some more mathematically operations 

In [178]:
a=np.arange(1,10)

In [179]:
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [180]:
# Sin value
np.sin(a)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 , -0.95892427,
       -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [ ]:
# cos value

In [181]:
np.cos(a)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362,  0.28366219,
        0.96017029,  0.75390225, -0.14550003, -0.91113026])

In [182]:
# Similarlly expontional of data
np.exp(a)

array([2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01,
       1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03,
       8.10308393e+03])

In [183]:
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [184]:
np.sum(a)

45

In [185]:
np.median(a)

5.0

In [186]:
#standered division
a.std()

2.581988897471611

In [192]:
a=np.arange(1,10).reshape(3,3)

In [193]:
#determination of a
np.linalg.det(a) #here linalg means linear alzebra

6.66133814775094e-16

In [194]:
#inverse 
np.linalg.inv(a)

array([[-4.50359963e+15,  9.00719925e+15, -4.50359963e+15],
       [ 9.00719925e+15, -1.80143985e+16,  9.00719925e+15],
       [-4.50359963e+15,  9.00719925e+15, -4.50359963e+15]])

In [195]:
#dot product of two index
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [198]:
b=a.T
b

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [199]:
np.dot(a,b)

array([[ 14,  32,  50],
       [ 32,  77, 122],
       [ 50, 122, 194]])