In [1]:
fileptr=open("file.txt","w")
fileptr.close()
print ("Created successfully")



Created successfully


In [2]:
fileptr=open ("file.txt","r")
if fileptr:
    print("file is opened successfully")
fileptr.close()

file is opened successfully


In [3]:
fileptr=open("file.txt","r")
content=fileptr.read(9)
print(type(content))
print(content)
fileptr.close()

<class 'str'>



In [4]:
fileptr=open("file.txt","w")
fileptr.write("Ravi kishore from apssdc")
fileptr.close()

In [5]:
fileptr=open('file.txt','a')
fileptr.write("\nspecified by python")
fileptr.close()

In [6]:
with open ("file.txt","r") as f:
    content=f.read()
    print(content)

Ravi kishore from apssdc
specified by python


In [7]:
fileptr=open("file.txt","r")
print("the file pointer is at byte",fileptr.tell())
content=fileptr.read()
print("after reading the file pointer at ", fileptr.tell())

the file pointer is at byte 0
after reading the file pointer at  45


In [8]:
import os
os.rename("file.txt","file1.txt")

PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'file.txt' -> 'file1.txt'

In [9]:
os.remove("kish.txt")

FileNotFoundError: [WinError 2] The system cannot find the file specified: 'kish.txt'

In [10]:
os.mkdir("new")

FileExistsError: [WinError 183] Cannot create a file when that file already exists: 'new'

I would be using files for lot of  my deeplearing models to import my data sets program at all the time
How can we input something into python
        the standered input 
        the useaul keyboard input

- What you may know as a file is slightly different in python

In [11]:
f=open("sample.txt","r")

FileNotFoundError: [Errno 2] No such file or directory: 'sample.txt'

In [13]:

def printFileDataLines(filename):
    f=open(filename,'r')
    for line in f:
        print(line,end= '')
    return
filename="file.txt"
printFileDataLines(filename)


Ravi kishore from apssdc
specified by python

In [15]:
filename=open("file.txt","r")
f=filename.read()
print(f)

Ravi kishore from apssdc
specified by python


In [18]:
filename=open("file.txt","r")
print(filename.tell())
f1=filename.read(10)
print(f1)
cposition=filename.seek(10)
print(cposition)

f=filename.read()
print(f)
print(filename.tell())

0
Ravi kisho
10
re from apssdc
specified by python
45


In [19]:
filename=open("file.txt","r")
print(filename.tell())
cposition=filename.seek(10,1)
print(cposition)

0


UnsupportedOperation: can't do nonzero cur-relative seeks

In [22]:
import io
print(io.DEFAULT_BUFFER_SIZE)

8192


In [27]:
filename=open("file.txt","w",buffering=100)

In [28]:
filename

<_io.TextIOWrapper name='file.txt' mode='w' encoding='cp1252'>

In [29]:
filename.encoding

'cp1252'

In [30]:
filename.mode

'w'

In [32]:
filename.writable()

True

In [33]:
filename.readable()

False

In [34]:
filename.seekable()

True

In [35]:
filename.name

'file.txt'

In [37]:
filename.line_buffering

False

### Numpy
- This is most commonly used python libraries for your datascience
- As it name Numpy it is break into two parts 
- Num  numerical  --- py--->python
- this is also called as Array oriented  computing( bcz in numpy just like list in python you will be able array kind of data structure
- This package mainly return for scientific computing & data analysis
- Basic numpy object:n dimentional array(ndarray)---->homogenous array
- all need to be samedata type
- usally the numpy array to keep eighter float or intiger datatype

### Why Numpy
- ----->fast
- ----->convinience
- ----->Less storage

In [42]:
import numpy as np
a=np.array([1,2,3])
a

array([1, 2, 3])

In [44]:
b=np.array([[1,2,3],[4,5,6]]) # its showing as matrix format
b

array([[1, 2, 3],
       [4, 5, 6]])

In [46]:
b.shape # This is gonna tell you what is the dimension of particular array
        # Horizontal part represents Row
        # Vertical part represents column

(2, 3)

In [47]:
a.shape # 1D array

(3,)

In [48]:
type(a)

numpy.ndarray

In [50]:
a.dtype # It"s return what kind of elements are present and so you can see that it"s telling that9 it"s an individual 32bit

dtype('int32')

In [51]:
b.dtype

dtype('int32')

In [52]:
b.ndim

2

In [53]:
print(type(a))

<class 'numpy.ndarray'>


In [56]:
# with out writing the form of list there is a command
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [57]:
 # practically showing difference of numpy and general program
c=range(1000)
# timeit is a function for checking time
%timeit [i**3 for i in c]

647 µs ± 16.5 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [68]:
c1=np.arange(10000)
%timeit c1**3


42.6 µs ± 1.57 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [69]:
# Another example 
l1=range(1000)
l2=[i**2 for i in range(1000)]
%timeit list(map(lambda x,y:x*y,l1,l2))


190 µs ± 2.9 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [71]:
a1=np.array(l1)
a2=np.array(l2)
%timeit a1*a2

2.68 µs ± 35.2 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [72]:
# i want to start with 2 not a zero
np.arange(2,10)

array([2, 3, 4, 5, 6, 7, 8, 9])

In [74]:
# I don't want to be contionus i just want to 2,4,6,8,...like that
np.arange(2,10,2) # This means give me the space of 2

array([2, 4, 6, 8])

In [76]:
# I want to fill it with zero using (3,2) dimentional array
np.zeros((3,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [78]:
np.ones((3,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [79]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [80]:
np.full((3,3),10)

array([[10, 10, 10],
       [10, 10, 10],
       [10, 10, 10]])

In [81]:
np.full((3,3),2.2)

array([[2.2, 2.2, 2.2],
       [2.2, 2.2, 2.2],
       [2.2, 2.2, 2.2]])

In [83]:
np.full((3,3),2.2,dtype=np.int) #Here the type conversition float - int

array([[2, 2, 2],
       [2, 2, 2],
       [2, 2, 2]])

In [85]:
# I want to insert the values diagonally
np.diag([1,2,3])

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [86]:
v=np.array([1,2,3])

In [87]:
v

array([1, 2, 3])

In [88]:
# I want to retuen same list in v as 3 rows and one column
np.tile(v,(3,1))

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [90]:
#if i want 3 rows and one column
np.tile(v,(3,2))

array([[1, 2, 3, 1, 2, 3],
       [1, 2, 3, 1, 2, 3],
       [1, 2, 3, 1, 2, 3]])

In [92]:
# i want to random vales
np.random.random()

0.637355246335078

In [93]:
#random value from 0 to 50
50*np.random.random()

28.049977344663056

In [94]:
# random value from 2 to 50
50*np.random.random() +2

2.901742377926018

In [95]:
# create matrix of random value
np.random.random([3,3])

array([[0.23162672, 0.80646482, 0.0989909 ],
       [0.29842978, 0.24789929, 0.43196006],
       [0.13371003, 0.06611838, 0.20812144]])